# ===============================================================
# =         PROD - Production Environment Configuration         =
# ===============================================================

# --- Database Settings ---
# Connect to the local MySQL database on the server
spring.datasource.url=jdbc:mysql://localhost:3306/caregiver_system?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456

# --- JPA / Hibernate Settings ---
# 'validate' is a safer choice in production. It ensures the schema matches
# the entities without making automatic changes.
#spring.jpa.hibernate.ddl-auto=validate
#
## Disable showing SQL queries in production logs to reduce noise.
#spring.jpa.show-sql=false

# Firebase Cloud Messaging
firebase.service-account.path=classpath:firebase-service-account.json

#gemini.api.key=AIzaSyCMEORQwC4wlrNVH4rPrVn3-TgZoALjJuE
gemini.api.key=AIzaSyCMEORQwC4wlrNVH4rPrVn3-TgZoALjJuE
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent


baidu.translate.appid=20260514002612997
baidu.translate.secret=pnll7mtuqUS7rCFgqnE5
baidu.translate.url=https://fanyi-api.baidu.com/api/trans/vip/translate

qwen.api.key=sk-19d91080507147f1ac178c93e8936aa6
qwen.api.url=https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
qwen.api.model=qwen-plus